apiVersion: v1
metadata:
  name: orders-service-Deployment
  labels:
    app: orders-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
        - name: orders-service
          image: houcine7/kata-mcommerce-app_orders-service
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: orders-app-Service
spec:
  type: NodePort
  selector:
    app: orders-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
