apiVersion: v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: houcine7/kata-mcommerce-app_payments-service
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: payment-app-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
