apiVersion: v1
kind: Deployment
metadata:
  name: products-service-Deployment
  labels:
    app: products-app
spec:
  selector:
    matchLabels:
      app: products-app
  replicas: 2
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-service
          image: houcine7/kata-mcommerce-app_products-service:latest
          ports:
            - containerPort: 3007

---
apiVersion: v1
kind: Service
metadata:
  name: products-app-Service
  labels:
    app: products-app
spec:
  type: NodePort
  selector:
    app: products-app
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
