name: Build and deploy to dockerhub

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, so your job can access it
      - name: checkout to repo
        uses: actions/checkout@v2

      # Using NodeJS as a runtime environment
      - name: Using nodeJS version 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      # Install pnpm globally as a package manager
      - name: Install pnpm
        run: npm i -g pnpm

      # Install monorepo dependencies
      - name: Install all dependecies
        run: pnpm i --no-frozen-lockfile

      # Build each service on the monorepo
      - name: Build all services
        run: |
          pnpm run build products-service
          pnpm run build orders-service
          pnpm run build payment-service
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out to the repo
        uses: actions/checkout@v2

      # installing podman
      - name: Installing podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

        # Login to dockerhub with podman
      - name: Login to dockerhub
        run: |
          podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      #Build and push images
      - name: Build and push images
        run: |
          podman compose build
          podman compose push
