name: Build and deploy to dockerhub

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, so your job can access it
      - name: checkout to repo
        uses: actions/checkout@v2

      # Using NodeJS as a runtime environment
      - name: Using nodeJS version 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      # Install pnpm globally as a package manager
      - name: Install pnpm
        run: npm i -g pnpm

      # Install monorepo dependencies
      - name: Install all dependecies
        run: pnpm i

      # Build each service on the monorepo
      - name: Build all services
        run: |
          pnpm run build products-service
          pnpm run build orders-service
          pnpm run build payment-service
