name: deploy images to docker hub
on:
  workflow_run:
    workflows:
      - 'Build workflow'
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out to the repo
        uses: actions/checkout@v2

      # installing podman
      - name: Installing podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

        # Installing docker-compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

        # Login to dockerhub with podman
      - name: Login to dockerhub
        run: |
          podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      # building and pushing images with docker-compose
      - name: Build and push images
        run: |
          docker-compose build

      # pushing images to dockerhub
      - name: Push images to dockerhub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
          echo "Pushing images to Docker Hub"
          images=($(docker images --format={{.Repository}}:{{.Tag}} | grep -E "products-service|orders-service|payment-service"))
          echo "$images"

          for image in "${images[@]}"; do
            echo "Pushing image: ${image} to Docker Hub"
            
            docker tag "$image" "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${image}"
            docker push "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${image}"
          done
